#!/bin/bash
# kernel/update <new sublevel>

if [ ! "$1" ]; then
	echo "kernel/update <new sublevel>"
	exit 1
fi

set -e

# load environment
source environment

# determine old version
cd `dirname $0`/linux
TEMPFILE=`mktemp`
head -n4 Makefile | sed -e 's/ //g' > $TEMPFILE
source $TEMPFILE
rm $TEMPFILE

# create patch directory if needed
if [ ! -e '../patches' ]; then
	mkdir ../patches
fi

# download patches
cd ../patches
for i in `seq "$SUBLEVEL" "$(($1 - 1))"`; do
	j="$((i + 1))"
	FILE="patch-$VERSION.$PATCHLEVEL.$i-$j.xz"
	if [ ! -f "$FILE" ]; then
		wget "https://www.kernel.org/pub/linux/kernel/v$VERSION.x/incr/$FILE"
	fi
done

# save config
cd ../linux
mv -v .config ../.config

# clean source
make distclean

# update source
for i in `seq "$SUBLEVEL" "$(($1 - 1))"`; do
	j="$((i + 1))"
	FILE="../patches/patch-$VERSION.$PATCHLEVEL.$i-$j.xz"
	if [ -f "$FILE" ]; then
		xzcat "$FILE" | patch -p1
	fi
done

# restore config
mv -v ../.config .config
